version: 2
jobs:
  build:
    machine: true
    docker:
      - image: honzatran/llvm-message-routing:latest
    steps:
        - checkout
        - run:
            name: "Pull submodules"
            command: |
                git submodule init
                git submodule update --remote
        - run: 
            name: cmake 
            command: |
                mkdir build 
                cd build 
                cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DLLVM_DIR=/llvm-release80-release -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -G Ninja 
        - run:
            name: generate_3rd_party_checksum
            command: |
                sh generate_checksum.sh
        - restore_cache:
            keys: 
                - 'ccache-{{ .Branch }}-{{ checksum "checksum.tmp" }}'
        - run:
            name: build
            command: |
                cd build
                ninja -j2
        - save_cache:
            key: 'ccache-{{ .Branch }}-{{ checksum "checksum.tmp" }}'
            paths: [ "/root/.ccache" ]
        - run:
            name: test
            environment:
                CTEST_OUTPUT_ON_FAILURE: 1
            command: | 
                cd build 
                ninja test
        - store_test_results:
            path: build/bin
