version: 2
jobs:
  build:
    docker:
      - image: honzatran/llvm-message-routing:latest
    steps:
        - checkout
        - run:
            name: "Pull submodules"
            command: |
                git submodule init
                git submodule update --remote
        - run: 
            name: cmake 
            command: |
                mkdir build 
                cd build 
                cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DLLVM_DIR=/llvm-release80-release -G Ninja 
        - restore_cache:
            keys: 
                'ccache- {{ .Branch }}'
        - run:
            name: build
            command: |
                cd build
                ninja -j1
        - run:
            name: test
            environment:
                CTEST_OUTPUT_ON_FAILURE: 1
            command: | 
                cd build 
                ninja test
        - store_test_results:
            path: build/bin
        - save_cache:
            key: 'ccache-{{ .Branch }}'
            paths: [ "/root/.ccache" ]


