version: 2
jobs:
  build:
    docker:
      - image: honzatran/llvm-message-routing:latest
    steps:
        - checkout
        - run: 
            name: cmake 
            command: |
                mkdir build 
                cd build 
                cmake .. -DCMAKE_BUILD_TYPE=RELEASE -G Ninja 
        - run:
            name: build
            command: |
                cd build
                ninja
        - run:
            name: test
            command: | 
                cd build 
                ninja lest

