// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: engine.proto
#ifndef GRPC_engine_2eproto__INCLUDED
#define GRPC_engine_2eproto__INCLUDED

#include "engine.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace engine {

// The greeting service definition.
class EngineService final {
 public:
  static constexpr char const* service_full_name() {
    return "engine.EngineService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Sends a greeting
    virtual ::grpc::Status RegisterTemplate(::grpc::ClientContext* context, const ::engine::TemplateRegisterRequest& request, ::engine::TemplateRegisterReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::engine::TemplateRegisterReply>> AsyncRegisterTemplate(::grpc::ClientContext* context, const ::engine::TemplateRegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::engine::TemplateRegisterReply>>(AsyncRegisterTemplateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::engine::TemplateRegisterReply>> PrepareAsyncRegisterTemplate(::grpc::ClientContext* context, const ::engine::TemplateRegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::engine::TemplateRegisterReply>>(PrepareAsyncRegisterTemplateRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // Sends a greeting
      virtual void RegisterTemplate(::grpc::ClientContext* context, const ::engine::TemplateRegisterRequest* request, ::engine::TemplateRegisterReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RegisterTemplate(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::engine::TemplateRegisterReply* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void RegisterTemplate(::grpc::ClientContext* context, const ::engine::TemplateRegisterRequest* request, ::engine::TemplateRegisterReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void RegisterTemplate(::grpc::ClientContext* context, const ::engine::TemplateRegisterRequest* request, ::engine::TemplateRegisterReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void RegisterTemplate(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::engine::TemplateRegisterReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void RegisterTemplate(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::engine::TemplateRegisterReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::engine::TemplateRegisterReply>* AsyncRegisterTemplateRaw(::grpc::ClientContext* context, const ::engine::TemplateRegisterRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::engine::TemplateRegisterReply>* PrepareAsyncRegisterTemplateRaw(::grpc::ClientContext* context, const ::engine::TemplateRegisterRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status RegisterTemplate(::grpc::ClientContext* context, const ::engine::TemplateRegisterRequest& request, ::engine::TemplateRegisterReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::engine::TemplateRegisterReply>> AsyncRegisterTemplate(::grpc::ClientContext* context, const ::engine::TemplateRegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::engine::TemplateRegisterReply>>(AsyncRegisterTemplateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::engine::TemplateRegisterReply>> PrepareAsyncRegisterTemplate(::grpc::ClientContext* context, const ::engine::TemplateRegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::engine::TemplateRegisterReply>>(PrepareAsyncRegisterTemplateRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void RegisterTemplate(::grpc::ClientContext* context, const ::engine::TemplateRegisterRequest* request, ::engine::TemplateRegisterReply* response, std::function<void(::grpc::Status)>) override;
      void RegisterTemplate(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::engine::TemplateRegisterReply* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void RegisterTemplate(::grpc::ClientContext* context, const ::engine::TemplateRegisterRequest* request, ::engine::TemplateRegisterReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void RegisterTemplate(::grpc::ClientContext* context, const ::engine::TemplateRegisterRequest* request, ::engine::TemplateRegisterReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void RegisterTemplate(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::engine::TemplateRegisterReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void RegisterTemplate(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::engine::TemplateRegisterReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::engine::TemplateRegisterReply>* AsyncRegisterTemplateRaw(::grpc::ClientContext* context, const ::engine::TemplateRegisterRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::engine::TemplateRegisterReply>* PrepareAsyncRegisterTemplateRaw(::grpc::ClientContext* context, const ::engine::TemplateRegisterRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_RegisterTemplate_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Sends a greeting
    virtual ::grpc::Status RegisterTemplate(::grpc::ServerContext* context, const ::engine::TemplateRegisterRequest* request, ::engine::TemplateRegisterReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_RegisterTemplate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RegisterTemplate() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_RegisterTemplate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterTemplate(::grpc::ServerContext* /*context*/, const ::engine::TemplateRegisterRequest* /*request*/, ::engine::TemplateRegisterReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegisterTemplate(::grpc::ServerContext* context, ::engine::TemplateRegisterRequest* request, ::grpc::ServerAsyncResponseWriter< ::engine::TemplateRegisterReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_RegisterTemplate<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_RegisterTemplate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_RegisterTemplate() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::engine::TemplateRegisterRequest, ::engine::TemplateRegisterReply>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::engine::TemplateRegisterRequest* request, ::engine::TemplateRegisterReply* response) { return this->RegisterTemplate(context, request, response); }));}
    void SetMessageAllocatorFor_RegisterTemplate(
        ::grpc::experimental::MessageAllocator< ::engine::TemplateRegisterRequest, ::engine::TemplateRegisterReply>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::engine::TemplateRegisterRequest, ::engine::TemplateRegisterReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_RegisterTemplate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterTemplate(::grpc::ServerContext* /*context*/, const ::engine::TemplateRegisterRequest* /*request*/, ::engine::TemplateRegisterReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* RegisterTemplate(
      ::grpc::CallbackServerContext* /*context*/, const ::engine::TemplateRegisterRequest* /*request*/, ::engine::TemplateRegisterReply* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* RegisterTemplate(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::engine::TemplateRegisterRequest* /*request*/, ::engine::TemplateRegisterReply* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_RegisterTemplate<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_RegisterTemplate<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_RegisterTemplate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RegisterTemplate() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_RegisterTemplate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterTemplate(::grpc::ServerContext* /*context*/, const ::engine::TemplateRegisterRequest* /*request*/, ::engine::TemplateRegisterReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_RegisterTemplate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RegisterTemplate() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_RegisterTemplate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterTemplate(::grpc::ServerContext* /*context*/, const ::engine::TemplateRegisterRequest* /*request*/, ::engine::TemplateRegisterReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegisterTemplate(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_RegisterTemplate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_RegisterTemplate() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RegisterTemplate(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_RegisterTemplate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterTemplate(::grpc::ServerContext* /*context*/, const ::engine::TemplateRegisterRequest* /*request*/, ::engine::TemplateRegisterReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* RegisterTemplate(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* RegisterTemplate(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RegisterTemplate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RegisterTemplate() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::engine::TemplateRegisterRequest, ::engine::TemplateRegisterReply>(std::bind(&WithStreamedUnaryMethod_RegisterTemplate<BaseClass>::StreamedRegisterTemplate, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_RegisterTemplate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RegisterTemplate(::grpc::ServerContext* /*context*/, const ::engine::TemplateRegisterRequest* /*request*/, ::engine::TemplateRegisterReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRegisterTemplate(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::engine::TemplateRegisterRequest,::engine::TemplateRegisterReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_RegisterTemplate<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_RegisterTemplate<Service > StreamedService;
};

}  // namespace engine


#endif  // GRPC_engine_2eproto__INCLUDED
