// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: engine.proto

#include "engine.pb.h"
#include "engine.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace engine {

static const char* EngineService_method_names[] = {
  "/engine.EngineService/SayHello",
};

std::unique_ptr< EngineService::Stub> EngineService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< EngineService::Stub> stub(new EngineService::Stub(channel));
  return stub;
}

EngineService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_SayHello_(EngineService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status EngineService::Stub::SayHello(::grpc::ClientContext* context, const ::engine::HelloRequest& request, ::engine::HelloReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SayHello_, context, request, response);
}

void EngineService::Stub::experimental_async::SayHello(::grpc::ClientContext* context, const ::engine::HelloRequest* request, ::engine::HelloReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, std::move(f));
}

void EngineService::Stub::experimental_async::SayHello(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::engine::HelloReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, std::move(f));
}

void EngineService::Stub::experimental_async::SayHello(::grpc::ClientContext* context, const ::engine::HelloRequest* request, ::engine::HelloReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, reactor);
}

void EngineService::Stub::experimental_async::SayHello(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::engine::HelloReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::engine::HelloReply>* EngineService::Stub::AsyncSayHelloRaw(::grpc::ClientContext* context, const ::engine::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::engine::HelloReply>::Create(channel_.get(), cq, rpcmethod_SayHello_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::engine::HelloReply>* EngineService::Stub::PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::engine::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::engine::HelloReply>::Create(channel_.get(), cq, rpcmethod_SayHello_, context, request, false);
}

EngineService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EngineService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EngineService::Service, ::engine::HelloRequest, ::engine::HelloReply>(
          std::mem_fn(&EngineService::Service::SayHello), this)));
}

EngineService::Service::~Service() {
}

::grpc::Status EngineService::Service::SayHello(::grpc::ServerContext* context, const ::engine::HelloRequest* request, ::engine::HelloReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace engine

